### ISSUE TITLE
getDepthTex() won't draw

### ISSUE THREAD

**Issue by spacepunkmedia** [prisonerjohn/ofxAzureKinect#1]
Trying to run example-streams and am unable to draw the texture returned from getDepthTex(). All of the other streams are working, and I have set my Windows environment variables properly. Any idea why that might be ? 

I'm running the most recent openFrameworks environment on  Visual Studio 2017

**Comment by prisonerjohn** [comment]
Is it giving you an error or you're just seeing black? 

If there are no errors, the image is probably being drawn but all pixel values are close to black. You can try to remap the colors with a shader or `ofxCvShortImage.convertToRange()`.

**Comment by prisonerjohn** [comment]
I'm going to close this since I haven't heard back. Feel free to reopen and add details if you're still having issues.
