### ISSUE TITLE
Vbo missmatch - point cloud example error

### ISSUE THREAD

**Issue by fred-dev** [prisonerjohn/ofxAzureKinect#12]
The point cloud example uses:

`kinectSettings.updateColor = true;`

When this is true Device.cpp  line 400 is:

```
if (this->bUpdateColor)
    {
	this->updatePointsCache(colorImg, this->colorToWorldImg);
    }
	else
    {
	this->updatePointsCache(depthImg, this->depthToWorldImg);
    }
```
This suggests it will create the points cache by iterating through the points in the colour frame and getting xyz values and texture coordinates from the pixlels in the full colour frame.

In the example however the full colour frame is not bound to the vbo, the colorInDepth tex is:

```
if (this->kinectDevice.getColorInDepthTex().isAllocated())
    {
	this->kinectDevice.getColorInDepthTex().bind();
    }

this->kinectDevice.getPointCloudVbo().draw( GL_POINTS, 0, this >kinectDevice.getPointCloudVbo().getNumVertices());

if (this->kinectDevice.getColorInDepthTex().isAllocated())
    {
	this->kinectDevice.getColorInDepthTex().unbind();
    }
```

Which would be appropriate if:
`this->updatePointsCache(depthImg, this->depthToWorldImg);`
were being called, but this will never be called when 
`kinectSettings.updateColor = true;`
And to have the `colorInDepthTex` needed for the texturing `kinectSettings.updateColor` must be set to true;

If I manually change the Device.cpp to only use:
`this->updatePointsCache(depthImg, this->depthToWorldImg);`
Then the results are correct, however 
`this->updatePointsCache(colorImg, this->colorToWorldImg);`
never returns the correct points, it should make a point cloud where the full colour texture can be bound and it would have the correct positions and texture coordinates.

I am not sure where the error comes from with the larger interpolated depth point cloud though.

Cheers

**Comment by prisonerjohn** [comment]
Hey! Thanks for this and sorry for addressing it so late. I finally got around to it and fixed this.
In case you're still interested, you can see how to use either the color or the depth resolution for the VBO in the point cloud example.
