### ISSUE TITLE
Player feature

### ISSUE THREAD

**Issue by paul-ferragut** [prisonerjohn/ofxAzureKinect#14]
I would like being able to play records with the addon.

With the SDK it is already possible to record as a .mkv containing color and depth (https://docs.microsoft.com/en-us/azure/kinect-dk/azure-kinect-recorder)

I will be looking into adding this feature but I am not sure how yet.  please let me know if you have any guidance and help

Thank you

**Comment by prisonerjohn** [comment]
Hi Paul, apologies for the delayed response, I didn't get any notifications from GitHub and never checked the issues. 
I just added this feature and an example to show how it works. Hopefully it's not too late for you to check it out.

**Comment by prisonerjohn** [comment]
I'll close this now, reopen it if you have any issues.

**Comment by paul-ferragut** [comment]
Thank you for the update!
