### ISSUE TITLE
Missing the sdk

### ISSUE THREAD

**Issue by tarrabass** [prisonerjohn/ofxAzureKinect#15]
fatal error C1083: Cannot open include file: 'k4a/k4a.hpp'
i installed the sdk, and configured the path in environnent variable

**Comment by waihinchan** [comment]
copy the sdk(both body and kinect) folder to your addon folder, this is working for me.

**Comment by prisonerjohn** [comment]
Were you able to resolve this? It might be a good idea to regenerate the project too.
I will close the issue and you can reopen if you are still having issues.
